MediaMarkt/HerstelBalieInventorAsp/InventorApp/InventorApp/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InventorApp.Models;

namespace InventorApp.Controllers
{
    public class DeviceController : Controller
    {
        // GET: Device

        private ActionsMethodes _aM = new ActionsMethodes();



        [HttpGet]
        public ActionResult CreateNewDevice()
        {
 
            return View();
        }

        [HttpPost]
        public ActionResult CreateNewDevice( HardWare hardWare)
        {
            if (ModelState.IsValid)
            {
                _aM.CreateDevice(hardWare);
               
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            if (id != 0)
            {
                
                return View(_aM.UpdateDevice(id));
            }
          return View();
       
        }

  
        public ActionResult Delete(int id)
        {
            if (id != 0)
            {
                _aM.DeleteDevice(id);
                return RedirectToAction("ListDevices");

            }
            return View();

        }

        [HttpPost]
        public ActionResult Update(HardWare hardWare)
        {
            if (ModelState.IsValid)
            {
                _aM.UpdateDevice(hardWare);
               return RedirectToAction("ListDevices");
            }
            return View();

        }

        public ActionResult ListDevices()
        {
            return View(_aM.GetAllHarware());
        }


        public ActionResult Details(int id)
        {
            return View(_aM.GetHardware(id));
        }

    }
}

MediaMarkt/HerstelBalieInventorAsp/InventorApp/InventorApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InventorApp.Models;
using ClassInventor;
using ClassInventor.Dal;
using ClassInventor.Model;

namespace InventorApp.Controllers
{
  
    public class HomeController : Controller
    {
        private InventorEntities _dB = new InventorEntities();
        // GET: Home
        public ActionResult Index()
        {


            return View();
        }

        //public ActionResult Index()
        //{
        //    try
        //    {

        //        //_dB.Database.Create();
        //        //ViewBag.DatabaseMessage = "Database is aangemaakt";

        //        VoegOnderdelenToe vt = new VoegOnderdelenToe();
        //        vt.VoegToenhardware();
        //        vt.VoegToenStock();
        //    }
        //    catch (Exception e)
        //    {

        //        ViewBag.DatabaseMessage = e.Message;
        //    }
        //    return View();
        //}


    }
}

MediaMarkt/HerstelBalieInventorAsp/InventorApp/InventorApp/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InventorApp.Models;

namespace InventorApp.Controllers
{
    public class RegisterController : Controller
    {
        private ActionsMethodes _aM = new ActionsMethodes();

        
        // GET: Register
        public ActionResult Register()
        {

            ViewBag.DateString = _aM.GetDate();

    
            ViewData["RegisterDev"] = _aM.GetAllStock();
            ViewData["Status"] = new SelectList(_aM.GetEnumList(), "Status");
           
            return View();
        }

        [HttpPost]
        public ActionResult Register(Inschrijven inschrijven, int id)
        {
        
            inschrijven.StockId = id;
            if (inschrijven != null)
            {
                ViewData["Status"] = new SelectList(_aM.GetEnumList(), "Status");
                _aM.CreateinInschrijven(inschrijven);
                ViewData["RegisterDev"] = _aM.GetAllStock();
               
                return View();
            }

            return View();

        }

        public ActionResult DoasList()
        {
            return View(_aM.Doas());
        }

    }
}

MediaMarkt/HerstelBalieInventorAsp/InventorApp/InventorApp/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutShared.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <p>

            <a href="@Url.Action("CreateNewDevice", "Device")" class="btn btn-sq-lg btn-danger">
                <i class="fa fa-plus-circle fa-5x"></i> <br />
                Create New <br>Device
            </a>
            <a href="@Url.Action("ListDevices","Device")" class="btn btn-sq-lg btn-danger">
                <i class="fa fa-list-ol fa-5x"></i><br />
                List <br>Devices
            </a>



            <a href="#" class="btn btn-sq-lg btn-danger">
                <i class="fa fa-star fa-5x"></i><br />
                Media <br>Markt
            </a>

        </p>


        <p>
            <a href="#" class="btn btn-sq-lg btn-danger">
                <i class="fa fa-star fa-5x"></i><br />
                Solutions <br> Conner
            </a>
            <a href="@Url.Action("CreateNewStock", "Stock")" class="btn btn-sq-lg btn-danger">
                <i class="fa fa-plus-square-o fa-5x"></i><br/>
                Create New <br>Stock
            </a>

            <a href="@Url.Action("ListStock", "Stock")" class="btn btn-sq-lg btn-danger">
                <i class="fa fa-list-ul fa-5x"></i><br/>
                List <br>Stock
            </a>

        

        </p>

        <p>

            <a href="@Url.Action("DoasList", "Register")" class="btn btn-sq-lg btn-danger">
                <i class="fa fa-plus-square-o fa-5x"></i><br />
                Register <br>DOA
            </a>

            <a href="#" class="btn btn-sq-lg btn-danger">
                <i class="fa fa-star fa-5x"></i><br />
                List <br>Registerd
            </a>
            <a href="@Url.Action("Register", "Register")" class="btn btn-sq-lg btn-danger">
                <i class="fa fa-list-ul fa-5x"></i><br />
                Register <br>Repaire
            </a>


        </p>
    </div>
</div>